### ISSUE TITLE
Custom configuration

### ISSUE THREAD

**Issue by Maydell** [AbiosGaming/go-sdk-v2#1]
For us it would be very useful if we could customize for instance what URL the SDK uses.

**Comment by patstrom** [comment]
To work against staging?

**Comment by Maydell** [comment]
Exactly, and maybe locally as well.

**Comment by patstrom** [comment]
So someting like a `SetBaseURL` function? That seems pretty silly to have in a client-facing SDK.

**Comment by Maydell** [comment]
We wouldn't need to document it, so I don't think it would be too weird. We could have it as an environment variable instead, so it doesn't show up as an exported function.

**Comment by patstrom** [comment]
Would creating a local branch solve it for you? I assume you only need one of them at a time. That's probably the easiest way.

**Comment by Maydell** [comment]
We are probably going to use it with glide so that would require everyone to make the change for every project using the SDK. But if you don't think it's a good idea adding it I'll just have to make it work some other way :)

**Comment by patstrom** [comment]
It's not that it would be particularly hard to implement, I'm just uncertain about adding undocumented features in an open-source SDK.  Adding it as a documented feature also seems a little sketchy since there is no use-case for a client to change the baseUrl.

**Comment by Maydell** [comment]
I agree that it would be weird to add it as a documented feature, but I was thinking of it as more of an undocumented debugging flag (albeit not really for debugging).

**Comment by patstrom** [comment]
Fixed in #4
