### ISSUE TITLE
Hitting timeouts in Abios

### ISSUE THREAD

**Issue by pbabbicola** [AbiosGaming/go-sdk-v2#14]
We were hitting several timeouts on abios due to the http timeout. [This change](https://github.com/pbabbicola/go-sdk-v2/blob/master/http_wrapper.go#L37) made it work for us. 

For replicability, this is the params we have on the request that was timing out:

```
	q := make(abios.Parameters)

	t := time.Now().Add(3 * (-24 * time.Hour))

	q.Add("games[]", "2")
	q.Add("games[]", "5")
	q.Add("with[]", "casters")
	q.Add("is_deleted", "false")
	q.Add("platforms[]", "1")
	q.Add("starts_before", "now")
	q.Add("starts_after", t.UTC().Format(RFC3339NoTimezone))
	q.Add("page", strconv.FormatInt(currentPage, 10))
```

It seems like a 20 s timeout is not enough. I forked it to make a quick fix since we are on a bit of a crunch, but thought I'd let you know anyways!

**Comment by patstrom** [comment]
Thank you for the report!

The 20 second timeout was kind of arbitrarily chosen. I've created an MR to increase to something more in-line with the server-side timeout!

**Comment by patstrom** [comment]
You can now upgrade to version `3.0.4`!

**Comment by pbabbicola** [comment]
Thanks!
